spring:
  application:
    name: exasol-github

github:
  api:
    base-url: https://api.github.com

repositories:
  exasol:
    - advanced-analytics-framework
    - bucketfs-java
    - compatibility-test-suite
    - docker-db
    - exasol-virtual-schema